package dev.kevalkanapriya.customtextfield.ui.textfield

import dev.kevalkanapriya.customtextfield.models.Country

var getLibCountries: List<Country> = mutableListOf(
    Country("ad", "+376", "Andorra"),
    Country("ae", "+971", "United Arab Emirates (UAE)"),
    Country("af", "+93", "Afghanistan"),
    Country("ag", "+1", "Antigua and Barbuda"),
    Country("ai", "+1", "Anguilla"),
    Country("al", "+355", "Albania"),
    Country("am", "+374", "Armenia"),
    Country("ao", "+244", "Angola"),
    Country("aq", "+672", "Antarctica"),
    Country("ar", "+54", "Argentina"),
    Country("as", "+1", "American Samoa"),
    Country("at", "+43", "Austria"),
    Country("au", "+61", "Australia"),
    Country("aw", "+297", "Aruba"),
    Country("ax", "+358", "Åland Islands"),
    Country("az", "+994", "Azerbaijan"),
    Country("ba", "+387", "Bosnia And Herzegovina"),
    Country("bb", "+1", "Barbados"),
    Country("bd", "+880", "Bangladesh"),
    Country("be", "+32", "Belgium"),
    Country("bf", "+226", "Burkina Faso"),
    Country("bg", "+359", "Bulgaria"),
    Country("bh", "+973", "Bahrain"),
    Country("bi", "+257", "Burundi"),
    Country("bj", "+229", "Benin"),
    Country("bl", "+590", "Saint Barthélemy"),
    Country("bm", "+1", "Bermuda"),
    Country("bn", "+673", "Brunei Darussalam"),
    Country("bo", "+591", "Bolivia, Plurinational State Of"),
    Country("br", "+55", "Brazil"),
    Country("bs", "+1", "Bahamas"),
    Country("bt", "+975", "Bhutan"),
    Country("bw", "+267", "Botswana"),
    Country("by", "+375", "Belarus"),
    Country("bz", "+501", "Belize"),
    Country("ca", "+1", "Canada"),
    Country("cc", "+61", "Cocos (keeling) Islands"),
    Country("cd", "+243", "Congo, The Democratic Republic Of The"),
    Country("cf", "+236", "Central African Republic"),
    Country("cg", "+242", "Congo"),
    Country("ch", "+41", "Switzerland"),
    Country("ci", "+225", "Côte D'ivoire"),
    Country("ck", "+682", "Cook Islands"),
    Country("cl", "+56", "Chile"),
    Country("cm", "+237", "Cameroon"),
    Country("cn", "+86", "China"),
    Country("co", "+57", "Colombia"),
    Country("cr", "+506", "Costa Rica"),
    Country("cu", "+53", "Cuba"),
    Country("cv", "+238", "Cape Verde"),
    Country("cw", "+599", "Curaçao"),
    Country("cx", "+61", "Christmas Island"),
    Country("cy", "+357", "Cyprus"),
    Country("cz", "+420", "Czech Republic"),
    Country("de", "+49", "Germany"),
    Country("dj", "+253", "Djibouti"),
    Country("dk", "+45", "Denmark"),
    Country("dm", "+1", "Dominica"),
    Country("do", "+1", "Dominican Republic"),
    Country("dz", "+213", "Algeria"),
    Country("ec", "+593", "Ecuador"),
    Country("ee", "+372", "Estonia"),
    Country("eg", "+20", "Egypt"),
    Country("er", "+291", "Eritrea"),
    Country("es", "+34", "Spain"),
    Country("et", "+251", "Ethiopia"),
    Country("fi", "+358", "Finland"),
    Country("fj", "+679", "Fiji"),
    Country("fk", "+500", "Falkland Islands (malvinas)"),
    Country("fm", "+691", "Micronesia, Federated States Of"),
    Country("fo", "+298", "Faroe Islands"),
    Country("fr", "+33", "France"),
    Country("ga", "+241", "Gabon"),
    Country("gb", "+44", "United Kingdom"),
    Country("gd", "+1", "Grenada"),
    Country("ge", "+995", "Georgia"),
    Country("gf", "+594", "French Guyana"),
    Country("gh", "+233", "Ghana"),
    Country("gi", "+350", "Gibraltar"),
    Country("gl", "+299", "Greenland"),
    Country("gm", "+220", "Gambia"),
    Country("gn", "+224", "Guinea"),
    Country("gp", "+450", "Guadeloupe"),
    Country("gq", "+240", "Equatorial Guinea"),
    Country("gr", "+30", "Greece"),
    Country("gt", "+502", "Guatemala"),
    Country("gu", "+1", "Guam"),
    Country("gw", "+245", "Guinea-bissau"),
    Country("gy", "+592", "Guyana"),
    Country("hk", "+852", "Hong Kong"),
    Country("hn", "+504", "Honduras"),
    Country("hr", "+385", "Croatia"),
    Country("ht", "+509", "Haiti"),
    Country("hu", "+36", "Hungary"),
    Country("id", "+62", "Indonesia"),
    Country("ie", "+353", "Ireland"),
    Country("il", "+972", "Israel"),
    Country("im", "+44", "Isle Of Man"),
    Country("is", "+354", "Iceland"),
    Country("in", "+91", "India"),
    Country("io", "+246", "British Indian Ocean Territory"),
    Country("iq", "+964", "Iraq"),
    Country("ir", "+98", "Iran, Islamic Republic Of"),
    Country("it", "+39", "Italy"),
    Country("je", "+44", "Jersey "),
    Country("jm", "+1", "Jamaica"),
    Country("jo", "+962", "Jordan"),
    Country("jp", "+81", "Japan"),
    Country("ke", "+254", "Kenya"),
    Country("kg", "+996", "Kyrgyzstan"),
    Country("kh", "+855", "Cambodia"),
    Country("ki", "+686", "Kiribati"),
    Country("km", "+269", "Comoros"),
    Country("kn", "+1", "Saint Kitts and Nevis"),
    Country("kp", "+850", "North Korea"),
    Country("kr", "+82", "South Korea"),
    Country("kw", "+965", "Kuwait"),
    Country("ky", "+1", "Cayman Islands"),
    Country("kz", "+7", "Kazakhstan"),
    Country("la", "+856", "Lao People's Democratic Republic"),
    Country("lb", "+961", "Lebanon"),
    Country("lc", "+1", "Saint Lucia"),
    Country("li", "+423", "Liechtenstein"),
    Country("lk", "+94", "Sri Lanka"),
    Country("lr", "+231", "Liberia"),
    Country("ls", "+266", "Lesotho"),
    Country("lt", "+370", "Lithuania"),
    Country("lu", "+352", "Luxembourg"),
    Country("lv", "+371", "Latvia"),
    Country("ly", "+218", "Libya"),
    Country("ma", "+212", "Morocco"),
    Country("mc", "+377", "Monaco"),
    Country("md", "+373", "Moldova, Republic Of"),
    Country("me", "+382", "Montenegro"),
    Country("mf", "+590", "Saint Martin"),
    Country("mg", "+261", "Madagascar"),
    Country("mh", "+692", "Marshall Islands"),
    Country("mk", "+389", "Macedonia (FYROM)"),
    Country("ml", "+223", "Mali"),
    Country("mm", "+95", "Myanmar"),
    Country("mn", "+976", "Mongolia"),
    Country("mo", "+853", "Macau"),
    Country("mp", "+1", "Northern Mariana Islands"),
    Country("mq", "+596", "Martinique"),
    Country("mr", "+222", "Mauritania"),
    Country("ms", "+1", "Montserrat"),
    Country("mt", "+356", "Malta"),
    Country("mu", "+230", "Mauritius"),
    Country("mv", "+960", "Maldives"),
    Country("mw", "+265", "Malawi"),
    Country("mx", "+52", "Mexico"),
    Country("my", "+60", "Malaysia"),
    Country("mz", "+258", "Mozambique"),
    Country("na", "+264", "Namibia"),
    Country("nc", "+687", "New Caledonia"),
    Country("ne", "+227", "Niger"),
    Country("nf", "+672", "Norfolk Islands"),
    Country("ng", "+234", "Nigeria"),
    Country("ni", "+505", "Nicaragua"),
    Country("nl", "+31", "Netherlands"),
    Country("no", "+47", "Norway"),
    Country("np", "+977", "Nepal"),
    Country("nr", "+674", "Nauru"),
    Country("nu", "+683", "Niue"),
    Country("nz", "+64", "New Zealand"),
    Country("om", "+968", "Oman"),
    Country("pa", "+507", "Panama"),
    Country("pe", "+51", "Peru"),
    Country("pf", "+689", "French Polynesia"),
    Country("pg", "+675", "Papua New Guinea"),
    Country("ph", "+63", "Philippines"),
    Country("pk", "+92", "Pakistan"),
    Country("pl", "+48", "Poland"),
    Country("pm", "+508", "Saint Pierre And Miquelon"),
    Country("pn", "+870", "Pitcairn Islands"),
    Country("pr", "+1", "Puerto Rico"),
    Country("ps", "+970", "Palestine"),
    Country("pt", "+351", "Portugal"),
    Country("pw", "+680", "Palau"),
    Country("py", "+595", "Paraguay"),
    Country("qa", "+974", "Qatar"),
    Country("re", "+262", "Réunion"),
    Country("ro", "+40", "Romania"),
    Country("rs", "+381", "Serbia"),
    Country("ru", "+7", "Russian Federation"),
    Country("rw", "+250", "Rwanda"),
    Country("sa", "+966", "Saudi Arabia"),
    Country("sb", "+677", "Solomon Islands"),
    Country("sc", "+248", "Seychelles"),
    Country("sd", "+249", "Sudan"),
    Country("se", "+46", "Sweden"),
    Country("sg", "+65", "Singapore"),
    Country("sh", "+290", "Saint Helena, Ascension And Tristan Da Cunha"),
    Country("si", "+386", "Slovenia"),
    Country("sk", "+421", "Slovakia"),
    Country("sl", "+232", "Sierra Leone"),
    Country("sm", "+378", "San Marino"),
    Country("sn", "+221", "Senegal"),
    Country("so", "+252", "Somalia"),
    Country("sr", "+597", "Suriname"),
    Country("ss", "+211", "South Sudan"),
    Country("st", "+239", "Sao Tome And Principe"),
    Country("sv", "+503", "El Salvador"),
    Country("sx", "+1", "Sint Maarten"),
    Country("sy", "+963", "Syrian Arab Republic"),
    Country("sz", "+268", "Swaziland"),
    Country("tc", "+1", "Turks and Caicos Islands"),
    Country("td", "+235", "Chad"),
    Country("tg", "+228", "Togo"),
    Country("th", "+66", "Thailand"),
    Country("tj", "+992", "Tajikistan"),
    Country("tk", "+690", "Tokelau"),
    Country("tl", "+670", "Timor-leste"),
    Country("tm", "+993", "Turkmenistan"),
    Country("tn", "+216", "Tunisia"),
    Country("to", "+676", "Tonga"),
    Country("tr", "+90", "Turkey"),
    Country("tt", "+1", "Trinidad &amp; Tobago"),
    Country("tv", "+688", "Tuvalu"),
    Country("tw", "+886", "Taiwan"),
    Country("tz", "+255", "Tanzania, United Republic Of"),
    Country("ua", "+380", "Ukraine"),
    Country("ug", "+256", "Uganda"),
    Country("us", "+1", "United States"),
    Country("uy", "+598", "Uruguay"),
    Country("uz", "+998", "Uzbekistan"),
    Country("va", "+379", "Holy See (vatican City State)"),
    Country("vc", "+1", "Saint Vincent &amp; The Grenadines"),
    Country("ve", "+58", "Venezuela, Bolivarian Republic Of"),
    Country("vg", "+1", "British Virgin Islands"),
    Country("vi", "+1", "US Virgin Islands"),
    Country("vn", "+84", "Vietnam"),
    Country("vu", "+678", "Vanuatu"),
    Country("wf", "+681", "Wallis And Futuna"),
    Country("ws", "4685", "Samoa"),
    Country("xk", "+383", "Kosovo"),
    Country("ye", "+967", "Yemen"),
    Country("yt", "+262", "Mayotte"),
    Country("za", "+27", "South Africa"),
    Country("zm", "+260", "Zambia"),
    Country("zw", "+263", "Zimbabwe"),
)